[package]
org = "ballerina"
name = "workflow"
version = "@project.version@"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/workflow-native-@project.version@.jar"
groupId = "io.ballerina.lib"
artifactId = "workflow-native"
version = "@project.version@"