[package]
org = "hasithaaravinda"
name = "workflow"
version = "0.1.0"
visibility="private"
distribution = "2201.12.10"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/workflow-native-0.1.0-SNAPSHOT.jar"
groupId = "io.ballerina.lib"
artifactId = "workflow-native"
version = "0.1.0-SNAPSHOT"